openapi: 3.0.3
info:
  title: Factorio Blueprint Generator server API
  description: |-
    This api provides blueprint generation services for the FBG-app.
  license:
    name: MIT License
    url: https://github.com/Buildasaurus/Factorio-Blueprint-Generator/blob/main/LICENSE
  version: 0.0.1
paths:
  /process:
    post:
      summary: Process some input
      description: Undefined behaviour on undefined input will somehow in the future genrate a blueprint
      operationId: server.process_string
      requestBody:
        description: Tell server how to generate a blueprint
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlueprintRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlueprintResponse'
        '400':
          description: No input string provided
  /compute-flow:
    post:
      summary: Compute max flow of a blueprint
      description: Given a blueprint string, this function will compute the max flow scenario and return max output and required input.
      operationId: server.find_blueprint_flow
      requestBody:
        description: Provide a blueprint that should be analyzed.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlueprintRequest'
        required: true
      responses:
        '200':
          description: Computed max flow for blueprint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeFlow'
        '400':
          description: No input string provided

components:
  schemas:
    BlueprintRequest:
      type: object
      properties:
        input_string:
          type: string
    BlueprintResponse:
      type: object
      properties:
        output_string:
          type: string
    NodeFlow:
      description: >
        Flow in and out of some area. This can be a single machine as well
        as a huge factory. Nodes can be set up in a hierarchy: You can
        think of a group of nodes as a single node.
      type: object
      properties:
        inputs:
          $ref: '#/components/schemas/EdgeFlow'
        outputs:
          $ref: '#/components/schemas/EdgeFlow'
    EdgeFlow:
      description: Flow between two flow nodes.
      type: array
      items:
        type: object
        properties:
          kind:
            description: Factorio internal name of item
            type: string
          rate:
            description: Flow speed in items per second
            type: number
            format: float
        example:
          kind:
            fast-inserter
          rate:
            0.01666666666
